name: CI

on:
  push:
    branches: main


jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        
      - name: Exporting Credentials
        run: |
          export ${{ secrets.AWS_ACCESS_KEY_ID }},
          export ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Apply
        run: terraform apply
