name: CI

on:
  push:
    branches: main


jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setaup Terraform
      - uses: hashicorp/setup-terraform@v2

      - name: Configure my AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id    :  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Apply
        run: terraform apply
